DROP DATABASE IF EXISTS burgers_db;
CREATE TABLE burgers_db;

CREATE TABLE burgers (
id INT AUTO_INCREMENT PRIMARY KEY,
burger_name VARCHAR(100) NOT NULL,
devoured BOOLEAN,
date TIMESTAMP
);

SELECT * FROM burgers;